%%_estacion(numero,nombre,conexion,tipo).
%%_conexion:
%%__normal
%%__transbordo
%%_tipo:
%%__paso
%%__terminal

%%_David_Pares_/_Vicente_Impares

estacion(1,pantitlan,transbordo,terminal).
estacion(1,zaragoza,normal,normal).
estacion(1,gomez_farias,normal,normal).
estacion(1,boulevard_puerto_aereo,normal,normal).
estacion(1,balbuena,normal,normal).
estacion(1,moctezuma,normal,normal).
estacion(1,san_lazaro,transbordo,normal).
estacion(1,candelaria,transbordo,normal).
estacion(1,merced,normal,normal).
estacion(1,pino_suarez,transbordo,normal).
estacion(1,isabel_la_catolica,normal,normal).
estacion(1,salto_del_agua,transbordo,normal).
estacion(1,balderas,transbordo,normal).
estacion(1,cuauhtemoc,normal,normal).
estacion(1,insurgentes,normal,normal).
estacion(1,sevilla,normal,normal).
estacion(1,chapultepec,normal,normal).
estacion(1,juanacatlan,normal,normal).
estacion(1,tacubaya,transbordo,normal).
estacion(1,observatorio,normal,terminal).

estacion(3,indios_verdes,normal,terminal).
estacion(3,deportivo_18_de_marzo,transbordo,normal).
estacion(3,potrero,normal,normal).
estacion(3,la_raza,transbordo,normal).
estacion(3,tlatelolco,normal,normal).
estacion(3,guerrero,transbordo,normal).
estacion(3,hidalgo,transbordo,normal).
estacion(3,juarez,normal,normal).
estacion(3,balderas,transbordo,normal).
estacion(3,ninos_heroes,normal,normal).
estacion(3,hospital_general,normal,normal).
estacion(3,centro_medico,transbordo,normal).
estacion(3,etiopia-plaza_de_la_transparencia,normal,normal).
estacion(3,eugenia,normal,normal).
estacion(3,division_del_norte,normal,normal).
estacion(3,zapata,transbordo,normal).
estacion(3,coyoacan,normal,normal).
estacion(3,viveros-derechos_humanos,normal,normal).
estacion(3,miguel_angel_de_quevedo,normal,normal).
estacion(3,copilco,normal,normal).
estacion(3,universidad,normal,terminal).

estacion(5,pantitlan,transbordo,terminal).
estacion(5,hangares,normal,normal).
estacion(5,terminal_aerea,normal,normal).
estacion(5,oceania,transbordo,normal).
estacion(5,aragon,normal,normal).
estacion(5,eduardo_molina,normal,normal).
estacion(5,consulado,transbordo,normal).
estacion(5,valle_gomez,normal,normal).
estacion(5,misterios,normal,normal).
estacion(5,la_raza,transbordo,normal).
estacion(5,autobuses_del_norte,normal,normal).
estacion(5,instituto_del_petroleo,transbordo,normal).
estacion(5,politecnico,normal,terminal).

estacion(7,el_rosario,transbordo,terminal).
estacion(7,aquiles_serdan,normal,normal).
estacion(7,refineria,normal,normal).
estacion(7,tacuba,transbordo,normal).
estacion(7,san_joaquin,normal,normal).
estacion(7,polanco,normal,normal).
estacion(7,auditorio,normal,nom).
estacion(7,constituyentes,normal,normal).
estacion(7,tacubaya,transbordo,normal).
estacion(7,san_pedro_de_los_pinos,normal,normal).
estacion(7,san_antonio,normal,normal).
estacion(7,mixcoac,transbordo,normal).
estacion(7,barranca_del_muerto,normal,terminal).

estacion(9,pantitlan,transbordo,terminal).
estacion(9,puebla,normal,normal).
estacion(9,iztacalco,normal,normal).
estacion(9,ciudad_deportiva,normal,normal).
estacion(9,velodromo,normal,normal).
estacion(9,mixiuhca,normal,normal).
estacion(9,jamaica,transbordo,normal).
estacion(9,chabacano,transbordo,normal).
estacion(9,lazaro_cardenas,normal,normal).
estacion(9,centro_medico,transbordo,normal).
estacion(9,chilpancingo,normal,normal).
estacion(9,patriotismo,normal,normal).
estacion(9,tacubaya,transbordo,terminal).

estacion(b,buenavista,transbordo,terminal).
estacion(b,guerrero,transbordo,normal).
estacion(b,garibaldi-lagunilla,normal,normal).
estacion(b,lagunilla,normal,normal).
estacion(b,tepit,normal,normal).
estacion(b,morelos,transbordo,normal).
estacion(b,san_lazaro,transbordo,normal).
estacion(b,ricardo_flores_magon,normal,normal).
estacion(b,romero_rubi,normal,normal).
estacion(b,oceania_gustavo_a_madero,transbordo,normal).
estacion(b,deportivo_oceani,normal,normal).
estacion(b,bosque_de_arago,normal,normal).
estacion(b,villa_de_arago,normal,normal).
estacion(b,nezahualcoyot,normal,normal).
estacion(b,impulsor,normal,normal).
estacion(b,rio_de_los_remedio,normal,normal).
estacion(b,muzquiz_ecatepec_de_morelo,normal,normal).
estacion(b,ecatepec,normal,normal).
estacion(b,olimpic,normal,normal).
estacion(b,plaza_arago,normal,normal).
estacion(b,ciudad_aztec,normal,terminal).

estacion(2,cuatro_caminos,normal,terminal).
estacion(2,panteones,normal,paso).
estacion(2,tacuba,transbordo,paso).
estacion(2,cuitlahuac,normal,paso).
estacion(2,popotla,normal,paso).
estacion(2,colegio_militar,normal,paso).
estacion(2,normal,normal,paso).
estacion(2,san_cosme,normal,paso).
estacion(2,revolucion,normal,paso).
estacion(2,hidalgo,transbordo,paso).
estacion(2,bellas_artes,transbordo,paso).
estacion(2,allende,normal,paso).
estacion(2,zocalo,normal,paso).
estacion(2,pino_suarez,transbordo,paso).
estacion(2,san_antonio_abad,normal,paso).
estacion(2,chabacano,transbordo,paso).
estacion(2,viaducto,normal,paso).
estacion(2,xola,normal,paso).
estacion(2,villa_de_cortes,normal,paso).
estacion(2,nativitas,normal,paso).
estacion(2,portales,normal,paso).
estacion(2,ermita,transbordo,paso).
estacion(2,general_anaya,normal,paso).
estacion(2,tasquena,normal,terminal).

estacion(4,martin_carrera,normal,terminal).
estacion(4,talisman,normal,paso).
estacion(4,bondojito,normal,paso).
estacion(4,consulado,normal,paso).
estacion(4,canal_del_norte,normal,paso).
estacion(4,morelos,normal,paso).
estacion(4,candelaria,normal,paso).
estacion(4,fray_servando,normal,paso).
estacion(4,jamaica,normal,paso).
estacion(4,santa_anita,normal,terminal).

estacion(6,el_rosario,transbordo,terminal).
estacion(6,tezozomoc,normal,paso).
estacion(6,uam_azcapotzalco,normal,paso).
estacion(6,ferreria_arena_cdmx,normal,paso).
estacion(6,norte_45,normal,paso).
estacion(6,vallejo,normal,paso).
estacion(6,instituto_del_petroleo,transbordo,paso).
estacion(6,lindavista,normal,paso).
estacion(6,deportivo_18_de_marzo,transbordo,paso).
estacion(6,la_villa_basilica,normal,paso).
estacion(6,martin_carrera,transbordo,terminal).

estacion(8,garibaldi_lagunilla,transbordo,terminal).
estacion(8,bellas_artes,transbordo,paso).
estacion(8,san_juan_de_letran,normal,paso).
estacion(8,salto_del_agua,transbordo,paso).
estacion(8,doctores,normal,paso).
estacion(8,obrera,normal,paso).
estacion(8,chabacano,transbordo,paso).
estacion(8,la_viga,normal,paso).
estacion(8,santa_anita,transbordo,paso).
estacion(8,coyuya,normal,paso).
estacion(8,iztacalco,normal,paso).
estacion(8,apatlaco,normal,paso).
estacion(8,aculco,normal,paso).
estacion(8,escuadron_201,normal,paso).
estacion(8,atlalilco,transbordo,paso).
estacion(8,iztapalapa,normal,paso).
estacion(8,cerro_de_la_estrella,normal,paso).
estacion(8,uam_i,normal,paso).
estacion(8,constitucion_de_1917,normal,terminal).

estacion(a,pantitlan,transbordo,terminal).
estacion(a,agricola_oriental,normal,paso).
estacion(a,canal_de_san_juan,normal,paso).
estacion(a,tepalcates,normal,paso).
estacion(a,guelatao,normal,paso).
estacion(a,penon_viejo,normal,paso).
estacion(a,acatitla,normal,paso).
estacion(a,santa_marta,normal,paso).
estacion(a,los_reyes,normal,paso).
estacion(a,la_paz,normal,terminal).

estacion(12,tlahuac,normal,terminal).
estacion(12,tlaltenco,normal,paso).
estacion(12,zapotitlan,normal,paso).
estacion(12,nopalera,normal,paso).
estacion(12,olivos,normal,paso).
estacion(12,tezonco,normal,paso).
estacion(12,periferico_oriente,normal,paso).
estacion(12,calle_11,normal,paso).
estacion(12,lomas_estrella,normal,paso).
estacion(12,san_andres_tomatlan,normal,paso).
estacion(12,culhuacan,normal,paso).
estacion(12,atlalilco,transbordo,paso).
estacion(12,mexicaltzingo,normal,paso).
estacion(12,ermita,transbordo,paso).
estacion(12,eje_central,normal,paso).
estacion(12,parque_de_los_venados,normal,paso).
estacion(12,zapata,transbordo,paso).
estacion(12,hospital_20_de_noviembre,normal,paso).
estacion(12,insurgentes_sur,normal,paso).
estacion(12,mixcoac,transbordo,terminal).




