%%_linea(numero,nombre,conexion,tipo).
%%_conexion:
%%__normal
%%__transbordo
%%_tipo:
%%__paso
%%__terminal

%%_David_Pares_/_Vicente_Impares

linea(1,pantitlán,transbordo,terminal).
linea(1,zaragoza,normal,normal).
linea(1,gómez_farías,normal,normal).
linea(1,boulevard_puerto_aéreo,normal,normal).
linea(1,balbuena,normal,normal).
linea(1,moctezuma,normal,normal).
linea(1,san_lázaro,transbordo,normal).
linea(1,candelaria,transbordo,normal).
linea(1,merced,normal,normal).
linea(1,pino_suárez,transbordo,normal).
linea(1,isabel_la_católica,normal,normal).
linea(1,salto_del_agua,transbordo,normal).
linea(1,balderas,transbordo,normal).
linea(1,cuauhtémoc,normal,normal).
linea(1,insurgentes,normal,normal).
linea(1,sevilla,normal,normal).
linea(1,chapultepec,normal,normal).
linea(1,juanacatlán,normal,normal).
linea(1,tacubaya,transbordo,normal).
linea(1,observatorio,normal,terminal).

linea(3,indios_verdes,normal,terminal).
linea(3,deportivo_18_de_marzo,transbordo,normal).
linea(3,potrero,normal,normal).
linea(3,la_raza,transbordo,normal).
linea(3,tlatelolco,normal,normal).
linea(3,guerrero,transbordo,normal).
linea(3,hidalgo,transbordo,normal).
linea(3,juárez,normal,normal).
linea(3,balderas,transbordo,normal).
linea(3,niños_héroes,normal,normal).
linea(3,hospital_general,normal,normal).
linea(3,centro_médico,transbordo,normal).
linea(3,etiopía-plaza_de_la_transparencia,normal,normal).
linea(3,eugenia,normal,normal).
linea(3,división_del_norte,normal,normal).
linea(3,zapata,transbordo,normal).
linea(3,coyoacán,normal,normal).
linea(3,viveros-derechos_humanos,normal,normal).
linea(3,miguel_ángel_de_quevedo,normal,normal).
linea(3,copilco,normal,normal).
linea(3,universidad,normal,terminal).

linea(5,pantitlán,transbordo,terminal).
linea(5,hangares,normal,normal).
linea(5,terminal_aérea,normal,normal).
linea(5,oceanía,transbordo,normal).
linea(5,aragón,normal,normal).
linea(5,eduardo_molina,normal,normal).
linea(5,consulado,transbordo,normal).
linea(5,valle_gómez,normal,normal).
linea(5,misterios,normal,normal).
linea(5,la_raza,transbordo,normal).
linea(5,autobuses_del_norte,normal,normal).
linea(5,instituto_del_petróleo,transbordo,normal).
linea(5,politécnico,normal,terminal).

linea(7,el_rosario,transbordo,terminal).
linea(7,aquiles_serdán,normal,normal).
linea(7,refinería,normal,normal).
linea(7,tacuba,transbordo,normal).
linea(7,san_joaquín,normal,normal).
linea(7,polanco,normal,normal).
linea(7,auditorio,normal,nom).
linea(7,constituyentes,normal,normal).
linea(7,tacubaya,transbordo,normal).
linea(7,san_pedro_de_los_pinos,normal,normal).
linea(7,san_antonio,normal,normal).
linea(7,mixcoac,transbordo,normal).
linea(7,barranca_del_muerto,normal,terminal).

linea(9,pantitlán,transbordo,terminal).
linea(9,puebla,normal,normal).
linea(9,iztacalco,normal,normal).
linea(9,ciudad_deportiva,normal,normal).
linea(9,velódromo,normal,normal).
linea(9,mixiuhca,normal,normal).
linea(9,jamaica,transbordo,normal).
linea(9,chabacano,transbordo,normal).
linea(9,lázaro_cárdenas,normal,normal).
linea(9,centro_médico,transbordo,normal).
linea(9,chilpancingo,normal,normal).
linea(9,patriotismo,normal,normal).
linea(9,tacubaya,transbordo,terminal).

linea(b,buenavista,transbordo,terminal).
linea(b,guerrero,transbordo,normal).
linea(b,garibaldi-lagunilla,normal,normal).
linea(b,lagunilla,normal,normal).
linea(b,tepit,normal,normal).
linea(b,morelos,transbordo,normal).
linea(b,san_lázaro,transbordo,normal).
linea(b,ricardo_flores_magón,normal,normal).
linea(b,romero_rubi,normal,normal).
linea(b,oceanía	gustavo_a_madero,transbordo,normal).
linea(b,deportivo_oceaní,normal,normal).
linea(b,bosque_de_aragó,normal,normal).
linea(b,villa_de_aragó,normal,normal).
linea(b,nezahualcóyot,normal,normal).
linea(b,impulsor,normal,normal).
linea(b,río_de_los_remedio,normal,normal).
linea(b,múzquiz	ecatepec_de_morelo,normal,normal).
linea(b,ecatepec,normal,normal).
linea(b,olímpic,normal,normal).
linea(b,plaza_aragó,normal,normal).
linea(b,ciudad_aztec,normal,terminal).

linea(2,cuatro_caminos,normal,terminal).
linea(2,panteones,normal,paso).
linea(2,tacuba,transbordo,paso).
linea(2,cuitlahuac,normal,paso).
linea(2,popotla,normal,paso).
linea(2,colegio_militar,normal,paso).
linea(2,normal,normal,paso).
linea(2,san_cosme,normal,paso).
linea(2,revolucion,normal,paso).
linea(2,hidalgo,transbordo,paso).
linea(2,bellas_artes,transbordo,paso).
linea(2,allende,normal,paso).
linea(2,zocalo,normal,paso).
linea(2,pino_suarez,transbordo,paso).
linea(2,san_antonio_abad,normal,paso).
linea(2,chabacano,transbordo,paso).
linea(2,viaducto,normal,paso).
linea(2,xola,normal,paso).
linea(2,villa_de_cortes,normal,paso).
linea(2,nativitas,normal,paso).
linea(2,portales,normal,paso).
linea(2,ermita,transbordo,paso).
linea(2,general_anaya,normal,paso).
linea(2,tasqueña,normal,terminal).

linea(4,martin_carrera,normal,terminal).
linea(4,talisman,normal,paso).
linea(4,bondojito,normal,paso).
linea(4,consulado,normal,paso).
linea(4,canal_del_norte,normal,paso).
linea(4,morelos,normal,paso).
linea(4,candelaria,normal,paso).
linea(4,fray_servando,normal,paso).
linea(4,jamaica,normal,paso).
linea(4,santa_anita,normal,terminal).

linea(6,el_rosario,transbordo,terminal).
linea(6,tezozomoc,normal,paso).
linea(6,uam_azcapotzalco,normal,paso).
linea(6,ferreria_arena_cdmx,normal,paso).
linea(6,norte_45,normal,paso).
linea(6,vallejo,normal,paso).
linea(6,instituto_del_petróleo,transbordo,paso).
linea(6,lindavista,normal,paso).
linea(6,deportivo_18_de_marzo,transbordo,paso).
linea(6,la_villa_basilica,normal,paso).
linea(6,martin_carrera,transbordo,terminal).

linea(8,garibaldi_lagunilla,transbordo,terminal).
linea(8,bellas_artes,transbordo,paso).
linea(8,san_juan_de_letran,normal,paso).
linea(8,salto_del_agua,transbordo,paso).
linea(8,doctores,normal,paso).
linea(8,obrera,normal,paso).
linea(8,chabacano,transbordo,paso).
linea(8,la_viga,normal,paso).
linea(8,santa_anita,transbordo,paso).
linea(8,coyuya,normal,paso).
linea(8,iztacalco,normal,paso).
linea(8,apatlaco,normal,paso).
linea(8,aculco,normal,paso).
linea(8,escuadron_201,normal,paso).
linea(8,atlalilco,transbordo,paso).
linea(8,iztapalapa,normal,paso).
linea(8,cerro_de_la_estrella,normal,paso).
linea(8,uam_i,normal,paso).
linea(8,constitucion_de_1917,normal,terminal).

linea(a,pantitlan,transbordo,terminal).
linea(a,agricola_oriental,normal,paso).
linea(a,canal_de_san_juan,normal,paso).
linea(a,tepalcates,normal,paso).
linea(a,guelatao,normal,paso).
linea(a,penon_viejo,normal,paso).
linea(a,acatitla,normal,paso).
linea(a,santa_marta,normal,paso).
linea(a,los_reyes,normal,paso).
linea(a,la_paz,normal,terminal).

linea(12,tlahuac,normal,terminal).
linea(12,tlaltenco,normal,paso).
linea(12,zapotitlan,normal,paso).
linea(12,nopalera,normal,paso).
linea(12,olivos,normal,paso).
linea(12,tezonco,normal,paso).
linea(12,periferico_oriente,normal,paso).
linea(12,calle_11,normal,paso).
linea(12,lomas_estrella,normal,paso).
linea(12,san_andres_tomatlan,normal,paso).
linea(12,culhuacan,normal,paso).
linea(12,atlalilco,transbordo,paso).
linea(12,mexicaltzingo,normal,paso).
linea(12,ermita,transbordo,paso).
linea(12,eje_central,normal,paso).
linea(12,parque_de_los_venados,normal,paso).
linea(12,zapata,transbordo,paso).
linea(12,hospital_20_de_noviembre,normal,paso).
linea(12,insurgentes_sur,normal,paso).
linea(12,mixcoac,transbordo,terminal).


